### ISSUE TITLE
69.1 to 70 update hassio won't boot

### ISSUE THREAD

**Issue by engle2192** [home-assistant/hassio#491]
After updating from 69.1 to 70 hassio won't start this is what the logs are showing? Any ideas before I clean install?

```
_    _                 _____ ____
 | |  | |               |_   _/ __ \
 | |__| | __ _ ___ ___    | || |  | |
 |  __  |/ _` / __/ __|   | || |  | |
 | |  | | (_| \__ \__ \_ _| || |__| |
 |_|  |_|\__,_|___/___(_)_____\____/


Our Cli:
$ hassio help

debug1: permanently_set_uid: 0/0
core-ssh:~# hassio ha logs
Error decoding json invalid character 'T' looking for beginning of value: Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 377, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 352, in main
    args = get_arguments()
  File "/usr/lib/python3.6/site-packages/homeassistant/__main__.py", line 85, in get_arguments
    import homeassistant.config as config_util
  File "/usr/lib/python3.6/site-packages/homeassistant/config.py", line 15, in <module>
    from homeassistant import auth
  File "/usr/lib/python3.6/site-packages/homeassistant/auth.py", line 116, in <module>
    @attr.s(slots=True)
AttributeError: module 'attr' has no attribute 's'
core-ssh:~#
```
