### ISSUE TITLE
Coinbase platform Invaid Config issue Hassio 0.64 upgrade

### ISSUE THREAD

**Issue by mchauhan1968** [home-assistant/hassio#390]
After I updated from Hassio from 0.63.3 to 0.64 getting below error message in error log. Please help. Thanks.

```
2018-02-26 22:13:09 ERROR (MainThread) [homeassistant.setup] Error during setup of component coinbase
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/coinbase.py", line 51, in setup
    api_key, api_secret)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/coinbase.py", line 77, in __init__
    from coinbase.wallet.client import Client
  File "/usr/lib/python3.6/site-packages/coinbase/wallet/client.py", line 38, in <module>
    from Crypto.Hash import SHA256
  File "/usr/lib/python3.6/site-packages/Crypto/Hash/SHA256.py", line 23, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 32, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string'
2018-02-26 22:13:39 WARNING (SyncWorker_7) [soco.data_structures_entry] DATA STRUCTURE UPGRADE FAIL. Unable to upgrade music library data structure to music service data structure because an entry is missing for DidlFavorite in DIDL_NAME_TO_QUALIFIED_MS_NAME. This should be reported as a bug.
```

**Comment by pvizeli** [comment]
That is fix with 0.64.1
